export const name = "Default";

// . = Grass  M = Mountain  C = City  F = Factory  H = HQ  R = Road  T = Tree  D = DirtRoad
export const data = `
TTTT.............MMM
TTT...............MM
TT.....RRRRR.......M
......RR...RR.......
.....RR.....RR......
.....R.......RR..MM.
.....R..MM....R..MM.
..RRRR..MM....R.....
.....R........RRRR..
.....R........R.....
.....RR......RR.....
......RR....RR......
.......RRRRRR.......
....................
.TT...........MMM...
.T.............MM...
MM..................
MM.......TT.........
.........TTT....MM..
..........T.....MMM.
`;
