export const name = "Default";

// . = Grass  M = Mountain  C = City  F = Factory  H = HQ  R = Road  T = Tree  D = DirtRoad
export const data = `
.T..TTT..M..MMM..H..
.T..TTT..M..MMM.....
.T..TTT..M..MMM.....
....................
.TTT..T..MMM..M.....
.TTT.....MMM........
.TTT..T..MMM..M.D...
.................D..
..M.......R..D...D..
..M.......R..D......
..M.......R..D......
..M.......R..D......
..........R.........
....................
...R......R......R..
...RRRRRRRRRRRRRR...
...R......R......R..
..........R.........
......RRRRRRRR......
.........H..........
`;
