export const name = "Default";

// . = Grass  M = Mountain  C = City  F = Factory  H = HQ  R = Road
export const data = `
..........H.........
.....FRRRRRRRRF.....
..........R.........
...R......R......R..
...CRRRRRRRRRRRRRC..
...R......R......R..
..........C.........
..........R.........
..M.......R......M..
..M...MMMR.MMM...M..
..M...MMM.RMMM...M..
..M.......R......M..
..........R.........
.........C..........
...R......R......R..
...CRRRRRRRRRRRRRC..
...R......R......R..
..........R.........
.....FRRRRRRRRF.....
.........H..........
`;
